version: '3'

services:
    nginx:
        build:
            context: .
            dockerfile: nginx.dockerfile
        container_name: synginx
        ports:
            - 80:80
        volumes:
            - ./:/var/www/html
        depends_on:
            - php
            - mysql
        networks:
            - sy-app-network

    php:
        build:
            context: .
            dockerfile: php71.dockerfile
        container_name: syphp
        volumes:
            - ./:/var/www/html
        networks:
            - sy-app-network

    mysql:
        image: mysql:5.7
        restart: always
        ports:
            - 3306:3306
        container_name: symysql
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: laravel
        networks:
        - sy-app-network

networks:
    sy-app-network:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: "10.2.1.0/16"