<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerN8YiE1u\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerN8YiE1u/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerN8YiE1u.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerN8YiE1u\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerN8YiE1u\App_KernelDevDebugContainer([
    'container.build_hash' => 'N8YiE1u',
    'container.build_id' => 'aefc134a',
    'container.build_time' => 1670791970,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerN8YiE1u');
