<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerN9Ku3J9\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerN9Ku3J9/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerN9Ku3J9.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerN9Ku3J9\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerN9Ku3J9\App_KernelDevDebugContainer([
    'container.build_hash' => 'N9Ku3J9',
    'container.build_id' => '9234d9c2',
    'container.build_time' => 1670362225,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerN9Ku3J9');
