<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZMG3Qez\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZMG3Qez/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZMG3Qez.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZMG3Qez\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZMG3Qez\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZMG3Qez',
    'container.build_id' => 'f5008046',
    'container.build_time' => 1670770199,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZMG3Qez');
